apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: fleet-nginx
    dev: testing
  name: webhook-test-disable-polling
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fleet-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fleet-nginx
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        ports:
        - containerPort: 80
